version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ADMIN_SECRET=${ADMIN_SECRET}
      - PORT=5000
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
